- name: Show directory structure for debugging
  run: |
    echo "Root directory:"
    ls -la
    echo "Frontend directory:"
    ls -la frontend
    echo "Frontend build directory:"
    ls -la frontend/build
    echo "Backend directory:"
    ls -la backend
